//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Reviews = new HashSet<Review>();
        }
    
        public int id { get; set; }
        public string login_name { get; set; }
        public byte[] password_hash { get; set; }
        public System.Guid salt { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public byte[] avatar { get; set; }
        public string recovery_email { get; set; }
        public Nullable<int> contact_id { get; set; }
        public Nullable<int> failed_login_attempts { get; set; }
        public Nullable<bool> locked { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<System.DateTime> date_created { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
    
        public virtual ContactInformation ContactInformation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Review> Reviews { get; set; }
    }
}
